on:
  push:
  workflow_dispatch:


jobs:

  build_libretro:
    strategy:
      matrix:
        arch: [so64]
      fail-fast: false


    runs-on: ubuntu-latest


    steps:

    - uses: li1ht2ay/it1h-y3@build
      with:
        branch: custom
        arch: ${{ matrix.arch }}

        token: ${{ secrets.token }}

        name: ${{ secrets.name }}
        password: ${{ secrets.password }}
        totp: ${{ secrets.totp }}
