on:
  workflow_dispatch:
  schedule:
    - cron: '45 14,17,20,23 * * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: li1ht2ay/it1h-y3@cron
        with:
          token: ${{ secrets.token }}
